# https://github.com/EnriqueBesuman/Docker_Config
#
# https://192.168.1.254:7171
#
version: "3.8"

services:
  comixed:
    image: comixed/comixed:latest
    container_name: "comixed"
    restart: unless-stopped
    ports:
      - 7171:7171
    volumes:
      - /COMIC/PRUEBAS:/library
      - /COMIC/PRUEBAS:/imports
      - /docker/comixed/database:/root/.comixed 
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels: # Labels para What's up Docker
      - wud.display.name=ComiXed
      - wud.display.icon=mdi:emoticon-happy-outline
