# https://github.com/EnriqueBesuman/Docker_Config
#
# http://192.168.1.254:3001
#
# Documentación: https://blog.parravidales.es/como-monitorizar-tu-nube-personal-con-uptime-kuma/
#
version: "3.8"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: kuma
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 3001:3001
    volumes:
      - /docker/kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # Para monitorizar contenedores
    environment:
      - TZ=${TZ}
#      - PUID=${PUID} # Con UID 1000 no se integra con Docker...
#      - PGID=${PGID} # Con GID 1000 no se integra con Docker...
    labels:
      - wud.display.name=Uptime Kuma
      - wud.display.icon=si:kuma

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.80.0/20
