version: "3.8"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: kuma
    restart: always
    ports:
      - 3001:3001
    volumes:
      - /docker/kuma:/app/data
    environment:
      - TZ=Europe/Madrid