# https://www.manelrodero.com/blog/instalacion-de-vaultwarden-en-docker

version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /docker/vaultwarden/config:/data/
    environment:
      - TZ=Europe/Madrid
      - DOMAIN=${VAULT_URL}
      - ADMIN_TOKEN=${VAULT_TOKEN}
    labels: # Labels para What's up Docker
      - wud.display.name=Vaultwarden
      - wud.display.icon=mdi:lock-outline
      #- wud.display.icon=si:vaultwarden

networks:
  default:
    name: gestion-red_customnetwork
    external: true
