# https://github.com/EnriqueBesuman/Docker_Config
#
# http://192.168.1.254:8443
#
# Documentación: https://hub.docker.com/r/linuxserver/code-server
#
version: "3.8"

services:
   
  vscode:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vscode
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 8443:8443
    volumes:
      - /docker/vscode/config:/config
      - /docker/homeassistant/config:/HASS_Config #Añadir las rutas locales a todos los repos que queramos
      - /docker/Docker_Config:/Docker_Config
      - /docker/Docker_Swarm_Config:/Docker_Swarm_Config
      - /home/userdocker/.ssh:/config/.ssh # Necesario para acceso write a los repos Github
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - PASSWORD=${VSCODE_PWD}
      - DEFAULT_WORKSPACE=/HASS_Config #optional
      - CS_DISABLE_GETTING_STARTED_OVERRIDE=true

    labels: # Labels para What's up Docker
      - wud.display.name=Visual Code
      - wud.display.icon=si:visualstudiocode

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.70.0/20
