# http://192.168.1.254:8443

version: "3.8"

services:
   
  vscode:
    image: lscr.io/linuxserver/code-server
    container_name: vscode
    restart: unless-stopped
    ports:
      - 8443:8443
    volumes:
      - /docker/vscode/config:/config
      - /docker/homeassistant/config:/config/workspace
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000
      - DEFAULT_WORKSPACE=/config/workspace #optional
    labels: # Labels para What's up Docker
      - wud.display.name=Visual Code
      - wud.display.icon=mdi:file-code
