# https://github.com/EnriqueBesuman/Docker_Config
#
# https://192.168.1.254:6969
#
# - Crear una nueva librería:
#   docker exec yacserver YACReaderLibraryServer create-library <library-name> /comics
# - Actualizar una librería (p.e. si se han añadido comics):
#   docker exec yacserver YACReaderLibraryServer update-library /comics
# - Listar librerías existentes:
#   docker exec yacserver YACReaderLibraryServer list-libraries
# - Eliminar una librería:
#   docker exec yacserver YACReaderLibraryServer remove-library <library-name>
#
version: "3.8"

services:
  yacserver:
    image: muallin/yacreaderlibrary-server-docker:latest
    container_name: yacserver
    restart: unless-stopped
    ports:
      - 6969:8080
    volumes:
      - /COMIC/COMIC10:/comics
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    entrypoint: [YACReaderLibraryServer create-library "Comic 10" /comics]
    labels: # Labels para What's up Docker
      - wud.display.name=YACServer
      - wud.display.icon=mdi:emoticon-happy-outline
