# http://192.168.1.254:5005
#
version: "3.8"

services:

  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    restart: unless-stopped
    ports:
      - 5005:5005
    volumes:
      - /docker/flame/config:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration feature
    environment:
      - PASSWORD=${FLAME_PWD}
