version: "3.8"

services:
# - Instalar SAI
#   https://blog.crstian.me/post/2022-08-05-integrar-sai-salicru-sps-500-one-en-home-assistant-con-docker/
#   https://networkupstools.org/docs/man/genericups.html
  nut-upsd:
    image: upshift/nut-upsd
    container_name: "nut-upsd"
    restart: unless-stopped
    ports:
      - 3493:3493
    environment:
      - TZ=Europe/Madrid
      - UPS_DRIVER=blazer_usb
      - API_USER=upsmon # Opcional, este es el user por defecto
      - API_PASSWORD=secret # Opcional, esta es la password por defecto
    devices:
      - /dev/bus/usb/001/007 # Para obtner el ubs: lsusb
    labels: # Labels para What's up Docker
      - wud.display.name=Network UPS Tools
      - wud.display.icon=mdi:car-battery

# - Eliminar entidades sin identificador único:
#   Ejecutar servicio "Recorder: Purge Entities"
#   Cerrar y volver a abrir sesión
# 
# - Instalar HACS:
#    En la consola del contenedor de HA: wget -O - https://get.hacs.xyz | bash -
#    Añadir integración HACS
# 
# - Notificaciones push:
#   https://www.home-assistant.io/integrations/html5
  homeassistant:
    depends_on: [nut-upsd]
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: "homeassistant"
    restart: unless-stopped
    ports: 
      - 8123:8123
    network_mode: host
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock #Necesario para Monitor Docker
    labels: # Labels para What's up Docker
      - wud.display.name=Home Assistant
      - wud.display.icon=mdi:home-assistant
    
#  node-red:
#    image: nodered/node-red:latest
#    container_name: nodered
#    ports:
#      - 1880:1880
#    environment:
#      - TZ=Europe/Madrid
#    volumes:
#      - /docker/nodered/config:/data
    
  vscode:
    depends_on: [homeassistant]
    image: lscr.io/linuxserver/code-server
    container_name: "vscode"
    restart: unless-stopped
    ports:
      - 8443:8443
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000
      - PASSWORD= #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD= #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN= #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /docker/vscode/config:/config
      - /docker/homeassistant/config:/config/workspace
    labels: # Labels para What's up Docker
      - wud.display.name=Visual Code
      - wud.display.icon=mdi:file-code
