version: "3.8"

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: "zigbee2mqtt"
    restart: unless-stopped
    ports:
      # Frontend port
      - 833:8080
    network_mode: host
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /docker/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    labels: # Labels para What's up Docker
      - wud.display.name=ZigBee2Mqtt
      - wud.display.icon=si:zigbee
