# https://www.youtube.com/watch?v=on9JfmpaUJ0&list=PLIr0LNE5Lat2RifKJbH2xaqIHPuFEpYnf&index=7
# https://www.homeautomationguy.io/docker-tips/configuring-the-mosquitto-mqtt-docker-container-for-use-with-home-assistant/
version: "3.8"

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: "mqtt"
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /docker/mqtt/config:/mosquitto/config
      - /docker/mqtt/data:/mosquitto/data
      - /docker/mqtt/log:/mosquitto/log
    labels: # Labels para What's up Docker
      - wud.display.name=MQTT
      - wud.display.icon=si:mqtt
