# INICIAR DESPUES DE NGINX!!!!!!!!!!!
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: "duplicati"
    restart: unless-stopped
    ports:
      - "8200:8200"
    networks:
      - nginx_customnetwork
      - default
    environment:
      - TZ=Europe/Madrid
      - PUID=0 # Importante mantener ID de root para evitar errores de acceso a los archivos
      - PGID=0
      - CLI_ARGS= # optional
    volumes:
      - /docker/duplicati/config:/config
      - /docker/BACKUPS:/backups
      - /docker:/docker
    labels: # Labels para What's up Docker
      - wud.display.name=Duplicati
      - wud.display.icon=mdi:cloud-upload-outline
networks:
  nginx_customnetwork:
    external: true      
