# Descargar raw con: wget -q https://raw.githubusercontent.com/EnriqueBesuman/Docker_Config/main/gestion-docker/portainer-compose.yaml -O portainer-compose.yaml
# Ejecutar con: docker-compose -f portainer-compose.yaml pull && docker-compose -p "portainer" -f portainer-compose.yaml up -d
#
# https://192.168.1.254:9443 
#
version: "3.2"

services:

  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    ports:
      - 9443:9443
    volumes:
      - /docker/portainer/config:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Madrid
#      - PUID=${PUID}
#      - PGID=${PGID}
    labels:
      - wud.display.name=Portainer
      - wud.display.icon=si:portainer

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.21.0/20

