# https://github.com/EnriqueBesuman/Docker_Config
#
# https://192.168.1.254:3000
#
version: "3.8"

services:

  wud:
    image: fmartinou/whats-up-docker:latest
    container_name: wud
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    ports:
      - 3030:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/whatsupdocker/config/:/store
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - WUD_REGISTRY_LSCR_TOKEN=${WUD_REGISTRY_LSCR_TOKEN}      
      - WUD_TRIGGER_SMTP_GMAIL_HOST=smtp.gmail.com
      - WUD_TRIGGER_SMTP_GMAIL_PORT=465
      - WUD_TRIGGER_SMTP_GMAIL_USER=${EMAIL_PERSONAL}
      - WUD_TRIGGER_SMTP_GMAIL_PASS=${WUD_EMAIL_PERSONAL_PWD}
      - WUD_TRIGGER_SMTP_GMAIL_FROM=${EMAIL_PERSONAL}
      - WUD_TRIGGER_SMTP_GMAIL_TO=${EMAIL_PERSONAL}
      - WUD_TRIGGER_SMTP_GMAIL_TLS_ENABLED=true       
      - WUD_TRIGGER_MQTT_WUD_URL=${MQTT_URL}
      - WUD_TRIGGER_MQTT_WUD_USER=${MQTT_USR}
      - WUD_TRIGGER_MQTT_WUD_PASSWORD=${MQTT_PWD}
      - WUD_TRIGGER_MQTT_WUD_HASS_ENABLED=true   
      - WUD_TRIGGER_SMTP_GMAIL_SIMPLETITLE=Hay una nueva versión de $${name} disponible!
      - WUD_TRIGGER_SMTP_GMAIL_SIMPLEBODY=El contenedor $${name} ha sido actualizado. Por favor, recréalo con Portainer cuando puedas... Gracias!
    labels: # Labels de What's up Docker
      - wud.display.name=What's up Docker
      - wud.display.icon=mdi:train-car-container

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/20
