# https://github.com/EnriqueBesuman/Docker_Config
#
# https://https://192.168.1.254:8123/
# https://ha.mykasa.mooo.com
#
# - Eliminar entidades sin identificador único:
#   Ejecutar servicio "Recorder: Purge Entities"
#   Cerrar y volver a abrir sesión
# 
# - Instalar HACS:
#    En la consola del contenedor de HA: wget -O - https://get.hacs.xyz | bash -
#    Añadir integración HACS
# 
# - Notificaciones push: https://www.home-assistant.io/integrations/html5
#
# - Lista de colores: https://www.rapidtables.com/web/color/RGB_Color.html
# - Iconos Material Design: https://materialdesignicons.com/
# - Iconos Simple Icons: https://simpleicons.org/
#
version: "3.8"

services:

  hass:
#    depends_on: 
#      - nut-upsd
#      - zigbee2mqtt
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: hass
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports: 
      - 8123:8123
    network_mode: host
    volumes:
      - /docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock #Necesario para Monitor Docker
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels: # Labels para What's up Docker
      - wud.display.name=Home Assistant
      - wud.display.icon=si:homeassistant
      - wud.tag.include=stable

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: nginx_proxy
    external: true
