# https://github.com/EnriqueBesuman/Docker_Config
#
# https://192.168.1.254:3030
#
# Repo Adward Home: https://hub.docker.com/r/adguard/adguardhome
# Documentación: https://cyberhost.uk/adguard-setup/
#
version: "3"

services:

  adguardhome:

    image: adguard/adguardhome
    container_name: "adguardhome"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
#      - PUID=${PUID}
#      - PGID=${PGID}
    ports:    
      # Plain DNS
#      - 53:53/tcp # plain DNS.
#      - 53:53/udp # plain DNS.
      # DNS-over-QUIC
#      - 784:784/udp 
#      - 853:853/udp
      # DNS-over-TLS
#      - 853:853/tcp
      # AdGuard Home Admin Panel as well as DNS-over-HTTPS
      - 3000:3000/tcp 
#      - 80:80/tcp
#      - 443:443/tcp
      # Only DHCP server 
#      - 67:67/udp 
#      - 68:68/tcp 
#      - 68:68/udp 
      # DNSCrypt
#      - 5443:5443/tcp 
#      - 5443:5443/udp 
#    network_mode: host # Only to use AdGuard Home as a DHCP server
    volumes:
      - /docker/adwardhome/work:/opt/adguardhome/work
      - /docker/adwardhome/config:/opt/adguardhome/conf
    labels: # Labels para What's up Docker
      - wud.display.name=Adward Home
      - wud.display.icon=mdi:block-helper

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: nginx_proxy
    external: true
