version: "3.8"

services:
#########
# NGINX #
#########
#
# http://192.168.1.254:81
#
# https://hub.docker.com/_/nginx

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 81:81
      - 80:80
      - 443:443
    networks:
      customnetwork:
        ipv4_address: 172.20.0.2 # Asignamos IP fija para permitir configuración de proxies de Home Assistant
    volumes:
      - /docker/nginx/config:/data
      - /docker/nginx/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Europe/Madrid
    labels: # Labels para What's up Docker
      - wud.display.name=Nginx
      - wud.display.icon=mdi:arrow-decision

##########
# PIHOLE #
##########
#
# https://192.168.1.254:831
#
# https://github.com/pi-hole/docker-pi-hole/ 
# https://docs.pi-hole.net/
# Listas de bloqueo https://blocklist.site/
#                   https://firebog.net/
# Probador de bloqueo https://canyoublockit.com/
#
# - ESTABLECER CONTRASEÑA: pihole -a -p contraseña
# - REINICIAR SERVICIO DNS: pihole restartdns

  pihole:
    image: pihole/pihole:latest
    container_name: "pihole"
    restart: unless-stopped
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    #ports:
    #  - 53:53/tcp
    #  - 53:53/udp
    #  - 67:67/udp # Only required if you are using Pi-hole as your DHCP server
    #  - 8080:80/tcp # Interfaz web
    network_mode: host
    volumes:
      - /docker/pihole/config:/etc/pihole
      - /docker/pihole/dnsmasq.d:/etc/dnsmasq.d
    environment:
      - TZ=Europe/Madrid
      - WEB_PORT=831
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    labels: # Labels para What's up Docker
      - wud.display.name=Pi Hole
      - wud.display.icon=mdi:pi-hole

##########
# WHOAMI #
##########
#
# https://192.168.1.254:2001
#
# https://hub.docker.com/r/traefik/whoami

  whoami:
    image: traefik/whoami
    container_name: whoami    
    command:
       # It tells whoami to start listening on 2001 instead of 80
       - --port=2001
       - --name=iamfoo
    labels: # Labels para What's up Docker
      - wud.display.name=Whoami
      - wud.display.icon=mdi:information-box-outline

      
networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
