# https://github.com/EnriqueBesuman/Docker_Config
#
# https://192.168.1.254:831
#
# Repo pihole: https://github.com/pi-hole/docker-pi-hole/ 
# Documentación: https://www.techaddressed.com/tutorials/install-pi-hole-docker/
# Listas de bloqueo: https://firebog.net/
# Probador de bloqueo: https://canyoublockit.com/
# Consejos de privacidad: https://www.privacytools.io/
#
# - ESTABLECER CONTRASEÑA: pihole -a -p contraseña
# - REINICIAR SERVICIO DNS: pihole restartdnsversion: "3.8"
#
services:

  pihole:
    image: pihole/pihole:latest
    container_name: "pihole"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    #ports:
    #  - 53:53/tcp
    #  - 53:53/udp
    #  - 67:67/udp # Only required if you are using Pi-hole as your DHCP server
    #  - 8080:80/tcp # Interfaz web
    #
    network_mode: host
    volumes:
      - /docker/pihole/config:/etc/pihole
      - /docker/pihole/dnsmasq.d:/etc/dnsmasq.d
    environment:
      - TZ=${TZ}
#      - PUID=${PUID}
#      - PGID=${PGID}
      - WEB_PORT=831
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    labels: # Labels para What's up Docker
      - wud.display.name=Pi Hole
      - wud.display.icon=si:pihole
      
#networks:
#  default:
#    name: nginx_proxy
#    external: true
