# https://github.com/EnriqueBesuman/Docker_Config
#
# https://192.168.1.254:2001
#
# https://hub.docker.com/r/traefik/whoami
#
version: "3.8"

services:

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    command:
       # It tells whoami to start listening on 2001 instead of 80
       - --port=2001
       - --name=iamfoo
    labels: # Labels para What's up Docker
      - wud.display.name=Whoami
      - wud.display.icon=mdi:information-box-outline
      - wud.tag.include=latest

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.160.0/20
